var bingoItems = [
// Add bingo items to this list. If you must use the double quote character (") in an item, escape it like this: \"
    //"Mic peak",
    //"Chat completes emote pyramid",
    "Legendary fish acquired",
    "Fifi gives into chat wanting to fish",
    "Where's the audio?!?",
    "Dead before round 1 closes",
    "melee or push kill",
    "Clip-worthy headshot",
    "Fifi is the current kill leader",
    "Custom fish acquired",
    "Forgot to split",
    "Any PB",
    "Lyss gets donowalled",
    "Fifi says OH SHOOT",
    "CLUTCH MOMENT",
    "Fifi rolls <50 on DTTO",
    "Fifi blames Harrison for rigging the timer rolls",
    "KAAAAATTTTT",
    "fifi drops a deez nuts",
    "Fifi didn't know that was a bingo square",
    "fifiFeels",
    "Fifi has to poop while queued for a match",
    "50+ month resub",
    "100+ month resub",
    "10 sub bomb",
    "50 sub bomb",
    "forgot or yells at Todd",
    "Goalie Goalllll",
    "Stunned silence",
    "Strimmer yells for mod attention",
    "Accidental Swear",
    "fifiDinkDonk announcement",
    "Fifi thinks about eating ice cweam", 
    "Webby on stream",
    "Fifi plays Barbie",
    "Damn RAT",
    "Rat in the chat",
    "Fifi forgets he's muted or unmuted",
    "Fifi says What is this lobby",
    "Fifi says That guy’s cheating",
    "Fifi says nuts",
    "Fifi says DUDE",
    "PAIN --- without love",
    "Fifi offers A Kiss on the Lips", 
    "Fifi says FRICK",
    "Fifi says HUHH",
    "Tempted to open cards",
    "Fifi jokingly requests a ban",
    "Fifi says linkydinky",
    "Fifi bleeps out curse words",
    "Hates on Overwatch",
    "Chauncey is unhelpful",
    "Questionable Innuendo",
    "Browser light mode",
    "Bad teammate in competitive game",
    "good teammate in competitive game",
    "Fifi says WOOOOOOW",
    //"Fifi says GOOOOOOD MOOORNING TO THE CHAAAAT”, (free)
    "Fifi calls someone a cutie",
    "Fifi needs more coffee",
    "Fifi says Ashes shut up",
    "Fifi says Let’s freakin go",
    "Fifi says I love this game",
    "Fifi says I hate this game",
    //"Fifi says nutsack",
    "Fifi apologizes for something",
    "Unlucky",
    "Wudder",
    "Scammed",
    "Fifi pulls a chase card",
    "Fifi sings where are the peepos"
    // For compatibility reasons, the very last item in the list should not have a comma after it.
];
