var bingoItems = [
// Add bingo items to this list. If you must use the double quote character (") in an item, escape it like this: \"
    "Mic peak",
    "Chat posts fifiMike pyramid", 
    "Chat posts groupStripp pyramid",
    "Fifi says OH SHOOT",
    "Fifi has to poop",
    "Somebody drops 10 gifted",
    "Strimmer yells for mod attention",
    "Accidental Swear",
    "fifiDinkDonk announcement",
    "Fifi thinks about eating ice cweam", 
    "Webby sits in Fifi’s lap",
    “Chat demands Fifi play a specific game”,
    //“Bot spam for buying followers/subs”,
    “Damn RAT”,
    “Fifi says What is this lobby”,
    “Fifi says That guy’s cheating”,
    “Fifi says DUDE”,
    “A Kiss on the Lips”, 
    “Fifi says FRICK”,
    “Fifi says HUHH”,
    “Tempted to open cards”,
    “Suggests ban on Linkfan or Sshrk”,
    “Fifi says linkydinky”,
    “Fifi bleeps out curse words”,
    “Hates on Overwatch”,
    “Chauncey is unhelpful”
    // For compatibility reasons, the very last item in the list should not have a comma after it.
];
